apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goalert.fullname" . }}
  labels:
    {{- include "goalert.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goalert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "goalert.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.hash }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHAT_DOMAIN
              value: {{ .Values.config.domain }}
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name:  {{ template "goalert.fullname" . }}
                  key: AUTH_TOKEN
            - name: APP_ID
              value: {{ .Values.config.appID | quote }}
            - name: APP_HASH
              value: {{ .Values.config.appHash | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
