district:
  mention_prefix: OrefAlarm
subdivision:
  replace:
    "1017": Acre - Industrial Zone
  industrial_zone: Industrial Zone
  regional_center: Regional Council
  regional_council: Regional Council
message:
  instructions: "{1}{2}{3} seek shelter"
  lockdown: Enter a building, lock the doors and close the windows
  uav_instructions: Following the entry of a suspicious aircraft, you must enter the protected space and remain there until the event is over
  uav_event_over: Hostile aircraft incursion event over
  secondsPrefix: "You have "
  secondsSuffix: " seconds to"
  immediate: Immediately
  rockets: Rocket and missile fire
  uav: Hostile aircraft incursion
  infiltration: Terrorist infiltration
  earthquake: Earthquake
  tsunami: Tsunami alert
  radiological: Radiological event
  biohazard: Hazardous Materials Event
