district:
  mention_prefix: צבעאדום
subdivision:
  replace:
    "1357": פי גלילות - מתחם
    "1379": פי גלילות - סינמה סיטי
    "277": גוש חלב - ג'ש
    "1367": גבעת הראל, גבעת הרואה
    "1309": בני יהודה, גבעת יואב
    "241": בני יהודה, גבעת יואב
    "751": ים המלח - מלונות מרכז
    "272": ים המלח - בתי מלון
  industrial_zone: אזור תעשייה
  regional_center: מרכז אזורי
ynet:
  drill: אזעקה במסגרת תרגיל
