district:
  mention_prefix: צבעאדום
subdivision:
  replace:
    "1357": פי גלילות - מתחם
    "1379": פי גלילות - סינמה סיטי
    "277": גוש חלב - ג'ש
    "1367": גבעת הראל, גבעת הרואה
    "1309": בני יהודה, גבעת יואב
    "241": בני יהודה, גבעת יואב
    "751": ים המלח - מלונות מרכז
    "272": ים המלח - בתי מלון
  industrial_zone: אזור תעשייה
  regional_center: מרכז אזורי
ynet:
  drill: אזעקה במסגרת תרגיל
message:
  instructions: "{1}{2}{3} היכנסו למרחב המוגן ושהו בו 10 דקות"
  lockdown: היכנסו למבנה, נעלו את הדלתות וסגרו את החלונות
  secondsPrefix: "תוך "
  secondsSuffix: " שניות"
  immediate: מיידית
  rockets: ירי רקטות וטילים
  uav: חדירת כלי טיס  עוין
  infiltration: חדירת מחבלים
  earthquake: רעידת אדמה
  tsunami: צונאמי
  radiological: אירוע רדיולוגי
  biohazard: חשיפה לחומרים מסוכנים

