config:
  authToken: xxx
  domain: http://mattermost-team-edition.chat.svc:8065
  team: nix
  channel: rockets

replicaCount: 1

image:
  repository: phntom/goalert
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.24"
  hash: "sha256:b0d260b44be7ce1dea948839d57bce246bb78b1976abc50612063e617ac37b07"

service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: https://kix.co.il
    nginx.ingress.kubernetes.io/cors-allow-methods: GET
    acme.kubernetes.io/enable: "true"
    acme.kubernetes.io/dns: "dns_cf"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Referrer-Policy: same-origin";
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($http_cf_connecting_ip != $remote_addr) { return 403; }
  hosts:
    - host: goalert.kix.co.il
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: goalert-kix-tls
      hosts:
        - goalert.kix.co.il

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#nodeSelector:
#  doks.digitalocean.com/node-pool: pool-production

tolerations: []

affinity: {}
